# Generated by Django 4.1.1 on 2022-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('url', models.CharField(max_length=240)),
                ('image_url', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
